#!/bin/bash
# Writes backend .env for local or remote development (CORS + Python service URL).

set -euo pipefail

DEFAULT_HOST="localhost"
DEFAULT_BACKEND_PORT=7331
DEFAULT_PYTHON_PORT=5001

read -p "Host [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

read -p "Frontend URL for CORS (e.g. http://localhost:3737) [http://${HOST}:3737]: " FRONTEND_URL
FRONTEND_URL=${FRONTEND_URL:-"http://${HOST}:3737"}

read -p "Python service URL [http://${HOST}:${DEFAULT_PYTHON_PORT}]: " PYTHON_URL
PYTHON_URL=${PYTHON_URL:-"http://${HOST}:${DEFAULT_PYTHON_PORT}"}

CORS_ALLOWED_ORIGINS="$FRONTEND_URL"

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
WHISPERRR_SERVICE_URL=${PYTHON_URL}
EOF

echo "Wrote .env with CORS_ALLOWED_ORIGINS and WHISPERRR_SERVICE_URL. Restart the API after changes."
