#!/bin/bash
# Writes backend .env for Spring (spring-dotenv): CORS for the SPA + Python transcription URL.

set -euo pipefail

DEFAULT_HOST="localhost"
DEFAULT_FRONTEND_PORT=3737
DEFAULT_PYTHON_PORT=5001

read -p "Frontend host as seen in the browser (Origin), e.g. localhost or a LAN IP [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

read -p "Frontend dev server port [${DEFAULT_FRONTEND_PORT}]: " FP
FP=${FP:-$DEFAULT_FRONTEND_PORT}

read -p "Python transcription service URL [http://127.0.0.1:${DEFAULT_PYTHON_PORT}]: " PYTHON_URL
PYTHON_URL=${PYTHON_URL:-"http://127.0.0.1:${DEFAULT_PYTHON_PORT}"}

FRONT_PRIMARY="http://${HOST}:${FP}"
# Common local Origin variants (localhost vs 127.0.0.1 vs IPv6 loopback).
CORS_ALLOWED_ORIGINS="${FRONT_PRIMARY},http://127.0.0.1:${FP},http://[::1]:${FP},http://localhost:${FP}"

cat > .env << EOF
# Generated by setup-env.sh — do not commit (.gitignore)
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
WHISPERRR_SERVICE_URL=${PYTHON_URL}
EOF

echo "Wrote .env with CORS_ALLOWED_ORIGINS and WHISPERRR_SERVICE_URL. Restart Spring after changes."
